FROM python:3.11

ARG PACKAGEDIR=/usr/local/lib/python3.11/site-packages/cravat

# Install utilities
RUN apt update && \
	apt install -y vim sqlite3 tabix supervisor nginx

RUN mkdir -p /var/log/supervisor

# Needed for gds-converter module
# Install latest R, following docs at https://cloud.r-project.org/bin/linux/debian/
RUN apt install -y --no-install-recommends software-properties-common dirmngr && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-key '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7' && \
    apt update && apt install -y r-base && \
    pip install rpy2 uwsgi
# Install R packages
RUN R -e 'options(Ncpus = parallel::detectCores()); install.packages("BiocManager"); BiocManager::install("SeqArray");'

# Install oc and python libraries
COPY . /src/open-cravat/
RUN pip install /src/open-cravat && \
	pip install \
		aiosqlite3 \
		scipy \
		pytabix \
		biopython \
		pandas \
		pyreadr

COPY docker/supervisor.conf /etc/supervisor/conf.d/supervisor.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf


# Run oc version to create some directories, then symlink to /mnt
RUN chown -R www-data $PACKAGEDIR

USER www-data
RUN oc version

USER root
RUN mv $PACKAGEDIR/conf         /mnt/conf         && ln -s /mnt/conf         $PACKAGEDIR/conf    && \
    mv $PACKAGEDIR/modules      /mnt/modules      && ln -s /mnt/modules      $PACKAGEDIR/modules && \
    mv $PACKAGEDIR/jobs         /mnt/jobs         && ln -s /mnt/jobs         $PACKAGEDIR/jobs    && \
    mv $PACKAGEDIR/logs         /mnt/logs         && ln -s /mnt/logs         $PACKAGEDIR/logs    && \
    mv $PACKAGEDIR/workspace    /mnt/workspace    && ln -s /mnt/workspace    $PACKAGEDIR/workspace

ENV CRAVAT_HOME $PACKAGEDIR

VOLUME /mnt/conf
VOLUME /mnt/modules
VOLUME /mnt/jobs
VOLUME /mnt/logs
VOLUME /mnt/workspace

VOLUME /tmp/job
WORKDIR /tmp/job

